### ISSUE TITLE
[FR] Consider compitable with "Folder Notes"

### ISSUE THREAD

**Issue by Moyf** [BogdanCodreanu/obsidian-moc-link-helper#2]
Hi! This is a really useful plugin, I love its concept and how it works to help maintain the MOC structure!

I'm using [Folder Notes](https://github.com/LostPaul/obsidian-folder-notes) plugin to organize my notes.

And the file structure would be:

- [Vlog] (folder)
  - vlog.md
  - other.md
  - another.md

And when using the **Link all** function, I will get "[[vlog/vlog]]" in the `up`, which I think `[[vlog]]` should be enough.

![image](https://github.com/user-attachments/assets/0dbe02d3-83fe-4cba-84e4-2745c9be36ba)

---

Well.. Suddenly I'm not very sure, maybe it's a problem related to shortest path link format?
![image](https://github.com/user-attachments/assets/99a6b358-9280-4892-9cab-affaf23116e2)

Anyway, I hope that there could be some way that the plugin could add "[[vlog]]" in the `up` when using **Link All**.

**Comment by BogdanCodreanu** [comment]
How many "Vlog" files do you have in the vault? 
It should put Vlog/Vlog only if there are multiple vlog files and it's required to specify also another path in the link.
I'll be running more tests right now on this

**Comment by BogdanCodreanu** [comment]
In the **folder notes** settings, what `Storage location` option do you have?
So you have 2 notes that are entitled Vlog. One for the folder and one for the note inside the Vlog folder. is this correct?

**Comment by Moyf** [comment]
> In the **folder notes** settings, what `Storage location` option do you have? So you have 2 notes that are entitled Vlog. One for the folder and one for the note inside the Vlog folder. is this correct?

My storage location option is **Inside the folder**:
![image](https://github.com/user-attachments/assets/cc579e3f-c3df-47e6-b90e-b02ee4216c56)

And I think I got only one note with the name/alias "Vlog":
![image](https://github.com/user-attachments/assets/988a7ecb-0428-4fed-831b-aefa2cd03c64)

![image](https://github.com/user-attachments/assets/3f34532b-86c6-4a27-9ebb-747c1771a91a)

**Comment by BogdanCodreanu** [comment]
and the MOC note is the one in `Vlog/Vlog`, right? I will try to reproduce it. Could you also show me what the plugin shows when you open the MOC note? 
Do not worry, we will definitely fix this to make it work nicely for your situation as well, even if it takes more days.

**Comment by Moyf** [comment]
> and the MOC note is the one in `Vlog/Vlog`, right? I will try to reproduce it. Could you also show me what the plugin shows when you open the MOC note? Do not worry, we will definitely fix this to make it work nicely for your situation as well, even if it takes more days.

Oh hi, yes, the MOC note is the Vlog.md (Vlog/vlog)

Here is my snapshot:
![image](https://github.com/user-attachments/assets/00977e78-cbbd-49de-b519-54e74d5bfeb7)

I manually changed the `up` value in children notes:
![image](https://github.com/user-attachments/assets/89d6e703-06b7-4f19-a9cb-31f30f293b2f)

frontmatter is:
```md
up:
  - "[[Vlog]]"
```

**Comment by Moyf** [comment]
> and the MOC note is the one in `Vlog/Vlog`, right? I will try to reproduce it. Could you also show me what the plugin shows when you open the MOC note? Do not worry, we will definitely fix this to make it work nicely for your situation as well, even if it takes more days.

Thank you, you are really very kind! 
Take your time, no rush  :D

**Comment by BogdanCodreanu** [comment]
Update the plugin and let me know if it works now.

**Comment by Moyf** [comment]
> Update the plugin and let me know if it works now.

Yes! It works now!

---

BTW, just a thought, do you think it would be useful for us to adding a link/unlink button for individual notes? 
![image](https://github.com/user-attachments/assets/52a392fb-1f59-4714-a28c-551772b7e6c3)
I have only recently started using this plugin and haven't had the chance to explore it in depth, so I'm not sure if this feature would be useful.

**Comment by BogdanCodreanu** [comment]
For this I have created the functionality to text select. Did you see it? I need to write a better readme file it seems..

[video](https://github.com/user-attachments/assets/b1a9003b-6dea-4e5c-b08c-a0f321998109)

Praise the sun!

**Comment by Moyf** [comment]
> For this I have created the functionality to text select. Did you see it? I need to write a better readme file it seems..
> 
>  Obsidian_Z0Vacw24MG.mp4 
> Praise the sun!

Oh..!
I saw the `You can also select text to choose specific notes` but I didn't recognize that I need to select in the Editing Area 😂
I tried to select text inside the plugin view and nothing happend lol

Now I get it, thank you!

And praise the sun!  ; )  ☀
