### ISSUE TITLE
[BUG] Error: dv.page only handles string and link paths

### ISSUE THREAD

**Issue by Moyf** [BogdanCodreanu/obsidian-moc-link-helper#3]
In specific Note, the plugin will continuously print Error:
![image](https://github.com/user-attachments/assets/5749fe28-29a3-41d6-9196-feee3c66b7b0)

Some debug info:
![image](https://github.com/user-attachments/assets/0eb1f2eb-12fa-44b2-b77a-9e62ff6b4d63)
![image](https://github.com/user-attachments/assets/a32dfcaa-370a-40eb-a6c1-a913124a2c37)

Is it normal? If you need more information, please let me know :D

**Comment by BogdanCodreanu** [comment]
Update the plugin and let me know if it's fixed.

**Comment by Moyf** [comment]
> Update the plugin and let me know if it's fixed.

Fxied, thank you 👍🏻
